language: php
sudo: false

php:
  - 5.6




before_script:
  - travis_retry composer install --no-interaction
  
script:
  - php vendor/codeception/codeception/codecept run unit --coverage-xml

after_script:
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover tests/_output/coverage.xml