language: php
sudo: false

php:
  - 5.6

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer install

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - sleep 5