language: php
sudo: false

php:
  - 5.5
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache/files


before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

script:
  - phpunit
